services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=graphdb
      - POSTGRES_USER=mhgh0st
      - POSTGRES_PASSWORD=MHgh.982

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=graphdb
      - DB_USER=mhgh0st
      - DB_PASSWORD=MHgh.982
      - DB_HOST=db

  frontend:
    build: ./FrontEnd
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    command: /bin/sh -c "bun x next build --webpack && bun start"

volumes:
  postgres_data:
